/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package softwareengineering;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hong
 */
public class Main extends javax.swing.JFrame {

    DefaultTableModel model;
    int count = 0;
    String sDate, eDate, id;

    /**
     * Creates new form Main
     */
    public Main() {
        DAO_Trade dao = new DAO_Trade();
        initComponents();
        dao.clear();
    }

    public Vector getColumn() {
        Vector col = new Vector();

        col.add("상품명");
        col.add("가격");
        col.add("갯수");

        return col;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("회원관리");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("상품관리");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("결제내역");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton9.setText("결제");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton4.setText("근무시간관리");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton11.setText("구매내역 추가");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "상품명", "가격", "수량"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton5.setText("로그인");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton3)))
                    .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if (evt.getSource() == jButton1) {
            new UserInterface().setVisible(true);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        if (evt.getSource() == jButton2) {
            new ItemInterface().setVisible(true);
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        new PaymentInterface().setVisible(true);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        if (evt.getSource() == jButton4) {
            new TimetableInterface().setVisible(true);
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        if (evt.getSource() == jButton5) {
            if (count == 0) {
                if (jTextField1.getText().equals("") || jTextField2.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "비어있어요!");
                } else {
                    String a = jTextField1.getText();
                    DTO_User dto = new DTO_User();
                    DAO_User dao = new DAO_User();
                    if (dao.getUserDTO(a) == null) {
                        JOptionPane.showMessageDialog(this, "잘못된 ID를 입력하셨습니다.");
                    } else {
                        dto = dao.getUserDTO(a);
                        if (!(dto.getName().trim().equals((jTextField2.getText())))) {
                            JOptionPane.showMessageDialog(this, "회원 ID와 이름을 바르게 입력해주십시요");
                        } else {
                            JOptionPane.showMessageDialog(this, "오늘 하루 수고!");
                            jTextField1.setVisible(false);
                            jTextField2.setVisible(false);
                            jButton5.setText("로그아웃");
                            count = 1;
                            setUser(a);
                            setSdate();
                        }
                    }
                }
            } else if (count == 1) {
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField1.setVisible(true);
                jTextField2.setVisible(true);
                jButton5.setText("로그인");
                count = 0;
                JOptionPane.showMessageDialog(this, "고생하셨습니다");
                setEdate();
                insertTime();
            }
        }
    }//GEN-LAST:event_jButton5MouseClicked
    public void setSdate() {
        Calendar cal = Calendar.getInstance();

        sDate = String.format("%04d-%02d-%02d %02d:%02d:%02d", cal.get(Calendar.YEAR),
                (cal.get(Calendar.MONTH) + 1),
                cal.get(Calendar.DAY_OF_MONTH),
                cal.get(Calendar.HOUR_OF_DAY),
                cal.get(Calendar.MINUTE),
                cal.get(Calendar.SECOND));
        JOptionPane.showMessageDialog(this, "근무시작 시간은" + sDate);
    }

    public void setEdate() {

        Calendar cal = Calendar.getInstance();

        eDate = String.format("%04d-%02d-%02d %02d:%02d:%02d", cal.get(Calendar.YEAR),
                (cal.get(Calendar.MONTH) + 1),
                cal.get(Calendar.DAY_OF_MONTH),
                cal.get(Calendar.HOUR_OF_DAY),
                cal.get(Calendar.MINUTE),
                cal.get(Calendar.SECOND));
        JOptionPane.showMessageDialog(this, "근무 끝 시간은" + eDate);
    }

    public String getPdate() {
        Calendar cal = Calendar.getInstance();
        String pDate = String.format("%04d-%02d-%02d %02d:%02d:%02d", cal.get(Calendar.YEAR),
                (cal.get(Calendar.MONTH) + 1),
                cal.get(Calendar.DAY_OF_MONTH),
                cal.get(Calendar.HOUR_OF_DAY),
                cal.get(Calendar.MINUTE),
                cal.get(Calendar.SECOND));

        return pDate;
    }

    public String getSdate() {
        return this.sDate;
    }

    public String getEdate() {
        return this.eDate;
    }

    public void setUser(String a) {
        this.id = a;
    }

    public String getUser() {
        return this.id;
    }

    private void insertTime() {
        DTO_Time dto = getTimeData();
        DAO_Time dao = new DAO_Time();
        boolean ok = dao.insertTime(dto);
        if (ok == false && !dto.getId().equals("")) {
            JOptionPane.showMessageDialog(this, "오류가 발생했습니다.!");
            return;
        }
        JOptionPane.showMessageDialog(this, "입력 되었습니다.");

    }

    public DTO_Time getTimeData() {
        DTO_Time dto = new DTO_Time();

        dto.setId(id);
        dto.setStime(getSdate());
        dto.setEtime(getEdate());

        return dto;
    }

    public DTO_Trade getViewData(String a, int b) {
        DTO_Trade dto = new DTO_Trade();
        DAO_Trade dao = new DAO_Trade();
        dto = dao.getTradeDTO(a);
        if (dto.getPrice() != 0) {
            int price = dto.getPrice();
            dto.setName(a);
            dto.setPrice(price);
            dto.setNum(b);
            return dto;
        } else {
            JOptionPane.showMessageDialog(this, "상품 명을 잘못 입력하셨습니다.");
        }
        return null;
    }

    private void insertTrade(String a, int b) {
        DTO_Trade dto = getViewData(a, b);
        DAO_Trade dao = new DAO_Trade();
        boolean ok = dao.insertTrade(dto);
        if (ok == false && !dto.getName().equals("")) {
            JOptionPane.showMessageDialog(this, "오류가 발생했습니다.!");
        }

    }

    public boolean card(int a) {
        DAO_Trade dao = new DAO_Trade();
        DAO_Card dao2 = new DAO_Card();
        boolean card = false;
        int carNum = Integer.parseInt(JOptionPane.showInputDialog("카드번호를 입력하세요"));
        if (!dao.adultP()) {
            if (dao2.getMoney(carNum, a)) {
                card = true;
            } else {
                card = false;
            }
        } else {
            if(dao2.getAge(carNum)){
            if (dao2.getMoney(carNum, a)) {
                card = true;
            } else {
                card = false;
            }
        }else{
            card = false;
            }
        }
        return card;
    }

    public DTO_Payment getPaymentData(int a, String b, String c, int d) {
        DTO_Payment dto = new DTO_Payment();
        dto.setPnum(a);
        dto.setId(b);
        dto.setDate(c);
        dto.setPtotal(d);
        return dto;
    }

    private void savePayment(int paymentNum, String u_id, String p_date, int p_total) {
        DTO_Payment dto = getPaymentData(paymentNum, u_id, p_date, p_total);
        DAO_Payment dao = new DAO_Payment();
        boolean ok = dao.insertPayment(dto);
        if (ok == false && dto.getId().equals("")) {
            JOptionPane.showMessageDialog(this, "오류가 발생했습니다.!");
            return;
        }

    }

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        DAO_Trade dao = new DAO_Trade();
        if (evt.getSource() == jButton11) {
            String a = JOptionPane.showInputDialog("상품 명을 입력하세요" + "");
            if(a.equals("")){
            JOptionPane.showMessageDialog(this,"상품명을 입력해주세요");}
            int b = Integer.parseInt(JOptionPane.showInputDialog("수량을 입력하세요" + ""));
            insertTrade(a, b);

            model = new DefaultTableModel(dao.getTradeList(), getColumn());
            jTable1.setModel(model);
        }

    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        String[] choices = {"현금", "카드"};
        if (evt.getSource() == jButton9) {
            DAO_Trade dao = new DAO_Trade();
            int sum = dao.Sum();
            int method = JOptionPane.showOptionDialog(this, "결제수단을 선택하세요", "Select One", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, choices, choices[0]);
            if (method == 0) {
                int money = Integer.parseInt(JOptionPane.showInputDialog("받은 금액을 입력하세요"));
                    if (money >= sum) {
                    JOptionPane.showMessageDialog(this, "결제가 완료되었습니다");
                    } else {
                        JOptionPane.showMessageDialog(this, (sum - money) + "원 부족합니다");
                             }
                    
            }   else if (method == 1) {
                if (card(sum)) {
                    JOptionPane.showMessageDialog(this, "결제가 완료되었습니다");
                    dao.clear();
                    model = new DefaultTableModel(dao.getTradeList(), getColumn());
                    jTable1.setModel(model);
                } else {
                    JOptionPane.showMessageDialog(this, "결제가 거부되었습니다");
                    return ;
                }
            }
            DAO_Payment dao2 = new DAO_Payment();
            int a = dao2.getPaymentNum();
            String date = getPdate();
            savePayment(a, getUser(), date, sum);
    }//GEN-LAST:event_jButton9MouseClicked
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
